spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:ecommerce}
      username: ${MONGODB_USERNAME:mongodb}
      password: ${MONGODB_PASSWORD:mongodb}
      authentication-database: admin
server:
  port: ${SERVER_PORT:8070}
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}